name: Flutter CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Flutter SDK
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.1'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Analyze the project
      # - name: Analyze project source
      #   run: dart analyze

      # Run unit tests
      - name: Run tests
        run: flutter test
